In [6]:
import pandas as pd
df = pd.DataFrame([[1, 2, 3],[4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"])
print(df)
print(df.index)

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9
Index(['x', 'y', 'z'], dtype='object')

In [7]:
df.describe()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

(3, 3)

In [8]:
df.loc['x':'y']

   A  B  C
x  1  2  3
y  4  5  6

In [9]:
df.iloc[1, 2] = 0 # change value of the element
df

   A  B  C
x  1  2  3
y  4  5  0
z  7  8  9

In [10]:
# you can also use the df.at[] or df.iat[], same thing
df.iat[1, 2]

np.int64(0)

In [11]:
df.sort_values("A", ascending=True)

   A  B  C
x  1  2  3
y  4  5  0
z  7  8  9

In [12]:
df.loc[df["C"] > 7, "A"]
df.loc[df["C"] > 7]

   A  B  C
z  7  8  9

In [13]:
df.loc[(df["C"] > 2) & (df["A"] < 2)] # the parantheses are a must

   A  B  C
x  1  2  3

In [14]:
df.loc["x", "C"] = "Hello"
df

C:\Users\Sachio\AppData\Local\Temp\ipykernel_35960\415091368.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Hello' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc["x", "C"] = "Hello"

   A  B      C
x  1  2  Hello
y  4  5      0
z  7  8      9

In [15]:
athlete = pd.DataFrame([["Max", "Jakarta", 3.3], ["James", "Surabaya", 3.7], ["Bryan", "semarang", 3.5], ["Rafael", "Bekasi", 4.0]], columns=["name", "born", "gpa"])
athlete

     name      born  gpa
0     Max   Jakarta  3.3
1   James  Surabaya  3.7
2   Bryan  semarang  3.5
3  Rafael    Bekasi  4.0

In [16]:
athlete[athlete['name'].str.contains("max|bryan", case=False, regex=True)] # regex = symbols like "|" which means OR

    name      born  gpa
0    Max   Jakarta  3.3
2  Bryan  semarang  3.5

In [17]:
athlete[athlete["born"].isin(["Jakarta", "Bekasi"]) & (athlete["name"].str.contains("max", case=False))]

  name     born  gpa
0  Max  Jakarta  3.3

In [18]:
# athlete[#COLUMN].str.startswith("max") is also a function
athlete.query("name == 'Max' and born == 'Jakarta'")

  name     born  gpa
0  Max  Jakarta  3.3

In [19]:
athlete['old_univ'] = "CUHK"
athlete.loc[[1,3],"univ"] = "HKUST"
athlete

     name      born  gpa old_univ   univ
0     Max   Jakarta  3.3     CUHK    NaN
1   James  Surabaya  3.7     CUHK  HKUST
2   Bryan  semarang  3.5     CUHK    NaN
3  Rafael    Bekasi  4.0     CUHK  HKUST

In [20]:
#another method, using numpy
import numpy as np
athlete['new_univ'] = np.where(athlete['gpa']>3.5, "MIT", "NUS")
athlete

     name      born  gpa old_univ   univ new_univ
0     Max   Jakarta  3.3     CUHK    NaN      NUS
1   James  Surabaya  3.7     CUHK  HKUST      MIT
2   Bryan  semarang  3.5     CUHK    NaN      NUS
3  Rafael    Bekasi  4.0     CUHK  HKUST      MIT

In [21]:
athlete.drop(columns=['univ'])

     name      born  gpa old_univ new_univ
0     Max   Jakarta  3.3     CUHK      NUS
1   James  Surabaya  3.7     CUHK      MIT
2   Bryan  semarang  3.5     CUHK      NUS
3  Rafael    Bekasi  4.0     CUHK      MIT

In [22]:
athlete['scholarship'] = np.where(athlete["gpa"]<=3.5, "no", "yes")
athlete.drop(columns=["old_univ"])
athlete

     name      born  gpa old_univ   univ new_univ scholarship
0     Max   Jakarta  3.3     CUHK    NaN      NUS          no
1   James  Surabaya  3.7     CUHK  HKUST      MIT         yes
2   Bryan  semarang  3.5     CUHK    NaN      NUS          no
3  Rafael    Bekasi  4.0     CUHK  HKUST      MIT         yes

In [23]:
athlete = athlete.drop(columns=["old_univ"])
athlete = athlete.drop(columns=["univ"])
athlete

     name      born  gpa new_univ scholarship
0     Max   Jakarta  3.3      NUS          no
1   James  Surabaya  3.7      MIT         yes
2   Bryan  semarang  3.5      NUS          no
3  Rafael    Bekasi  4.0      MIT         yes

In [24]:
athlete.rename(columns={"new_univ":"univ"}, inplace=True)

In [25]:
athlete["born_date"] = ['2007-12-12', '2007-11-11', '2007-10-10', '2007-09-09']
athlete

     name      born  gpa univ scholarship   born_date
0     Max   Jakarta  3.3  NUS          no  2007-12-12
1   James  Surabaya  3.7  MIT         yes  2007-11-11
2   Bryan  semarang  3.5  NUS          no  2007-10-10
3  Rafael    Bekasi  4.0  MIT         yes  2007-09-09

In [26]:
athlete["year_born"] = athlete["born_date"].str.split("-").str[0]
athlete

     name      born  gpa univ scholarship   born_date year_born
0     Max   Jakarta  3.3  NUS          no  2007-12-12      2007
1   James  Surabaya  3.7  MIT         yes  2007-11-11      2007
2   Bryan  semarang  3.5  NUS          no  2007-10-10      2007
3  Rafael    Bekasi  4.0  MIT         yes  2007-09-09      2007

In [27]:
athlete["born_datetime"] = pd.to_datetime(athlete["born_date"], format="%Y-%m-%d")
athlete

     name      born  gpa univ scholarship   born_date year_born born_datetime
0     Max   Jakarta  3.3  NUS          no  2007-12-12      2007    2007-12-12
1   James  Surabaya  3.7  MIT         yes  2007-11-11      2007    2007-11-11
2   Bryan  semarang  3.5  NUS          no  2007-10-10      2007    2007-10-10
3  Rafael    Bekasi  4.0  MIT         yes  2007-09-09      2007    2007-09-09

In [28]:
# multiple conditions using apply lambda or  a def
athlete['level'] = athlete['gpa'].apply(lambda x: "High" if x > 3.6 else ("Average" if 3.4 < x <= 3.6 else "low"))
athlete

,name,born,gpa,univ,scholarship,born_date,year_born,born_datetime,level
0,Max,Jakarta,3.3,NUS,no,2007-12-12,2007,2007-12-12,low
1,James,Surabaya,3.7,MIT,yes,2007-11-11,2007,2007-11-11,High
2,Bryan,semarang,3.5,NUS,no,2007-10-10,2007,2007-10-10,Average
3,Rafael,Bekasi,4.0,MIT,yes,2007-09-09,2007,2007-09-09,High

In [29]:
new_info = pd.DataFrame([[175, 70], [178, 72], [170, 68], [168, 60]], columns = ["height", "weight"], index=["Max", "James", "Bryan", "Rafael"])
new_info

        height  weight
Max        175      70
James      178      72
Bryan      170      68
Rafael     168      60

In [30]:
#matching left_on and right_on
athlete_new = pd.merge(athlete, new_info, left_on="name", right_on=new_info.index, how="left")
athlete_new

,name,born,gpa,univ,scholarship,born_date,year_born,born_datetime,level,height,weight
0,Max,Jakarta,3.3,NUS,no,2007-12-12,2007,2007-12-12,low,175,70
1,James,Surabaya,3.7,MIT,yes,2007-11-11,2007,2007-11-11,High,178,72
2,Bryan,semarang,3.5,NUS,no,2007-10-10,2007,2007-10-10,Average,170,68
3,Rafael,Bekasi,4.0,MIT,yes,2007-09-09,2007,2007-09-09,High,168,60

In [31]:
add_on = pd.DataFrame([["Blake", "USA", 2.5], ["Tyrone", "Jamaica", 3.0], ["Ben", "England", 2.9]], columns=["name", "born", "gpa"])

In [32]:
students = pd.concat([athlete_new, add_on]) 
students

,name,born,gpa,univ,scholarship,born_date,year_born,born_datetime,level,height,weight
0,Max,Jakarta,3.3,NUS,no,2007-12-12,2007,2007-12-12,low,175.0,70.0
1,James,Surabaya,3.7,MIT,yes,2007-11-11,2007,2007-11-11,High,178.0,72.0
2,Bryan,semarang,3.5,NUS,no,2007-10-10,2007,2007-10-10,Average,170.0,68.0
3,Rafael,Bekasi,4.0,MIT,yes,2007-09-09,2007,2007-09-09,High,168.0,60.0
0,Blake,USA,2.5,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,Tyrone,Jamaica,3.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,Ben,England,2.9,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [33]:
students.fillna(students['year_born'].interpolate)
students

,name,born,gpa,univ,scholarship,born_date,year_born,born_datetime,level,height,weight
0,Max,Jakarta,3.3,NUS,no,2007-12-12,2007,2007-12-12,low,175.0,70.0
1,James,Surabaya,3.7,MIT,yes,2007-11-11,2007,2007-11-11,High,178.0,72.0
2,Bryan,semarang,3.5,NUS,no,2007-10-10,2007,2007-10-10,Average,170.0,68.0
3,Rafael,Bekasi,4.0,MIT,yes,2007-09-09,2007,2007-09-09,High,168.0,60.0
0,Blake,USA,2.5,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,Tyrone,Jamaica,3.0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,Ben,England,2.9,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [34]:
students.groupby(['univ','level']).agg({'gpa':'mean','height':'mean'})

               gpa  height
univ level
MIT  High     3.85   173.0
NUS  Average  3.50   170.0
     low      3.30   175.0

In [35]:
sports = pd.DataFrame([['volleyball', 'Max'], ['basketball', 'James'], ['basketball', 'Bryan'], ['volleyball', 'Rafael'], ['volleyball', 'Blake'], ['basketball', 'Tyrone'], ['volleyball', 'Ben']], columns=["sports", 'name'])

In [36]:
students = pd.merge(students, sports, left_on='name', right_on='name', how="left")

In [37]:
pivot = students.pivot(columns='sports', index='name', values='gpa')
pivot

sports  basketball  volleyball
name
Ben            NaN         2.9
Blake          NaN         2.5
Bryan          3.5         NaN
James          3.7         NaN
Max            NaN         3.3
Rafael         NaN         4.0
Tyrone         3.0         NaN

In [38]:
pivot.mean(axis=1)

name
Ben       2.9
Blake     2.5
Bryan     3.5
James     3.7
Max       3.3
Rafael    4.0
Tyrone    3.0
dtype: float64

In [44]:
students['scholarship'] = np.where(students["gpa"]<=3.5, "no", "yes")
students['level'] = students['gpa'].apply(lambda x: "High" if x > 3.6 else ("Average" if 3.4 < x <= 3.6 else "low"))
students

,name,born,gpa,univ,scholarship,born_date,year_born,born_datetime,level,height,weight,sports
0,Max,Jakarta,3.3,NUS,no,2007-12-12,2007,2007-12-12,low,175.0,70.0,volleyball
1,James,Surabaya,3.7,MIT,yes,2007-11-11,2007,2007-11-11,High,178.0,72.0,basketball
2,Bryan,semarang,3.5,NUS,no,2007-10-10,2007,2007-10-10,Average,170.0,68.0,basketball
3,Rafael,Bekasi,4.0,MIT,yes,2007-09-09,2007,2007-09-09,High,168.0,60.0,volleyball
4,Blake,USA,2.5,NaN,no,NaN,NaN,NaT,low,NaN,NaN,volleyball
5,Tyrone,Jamaica,3.0,NaN,no,NaN,NaN,NaT,low,NaN,NaN,basketball
6,Ben,England,2.9,NaN,no,NaN,NaN,NaT,low,NaN,NaN,volleyball

In [45]:
students.to_csv('students.csv', index=False)